CREATE OR REPLACE PROCEDURE add_foreign_key AS
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PRESCRIPTION_DETAIL ADD CONSTRAINT fk_prescription FOREIGN KEY (PRESCRIPTION_ID) REFERENCES PRESCRIPTION(PRESCRIPTION_ID)';
END add_foreign_key;
/

BEGIN
  add_foreign_key;
END;
/