CREATE OR REPLACE PROCEDURE add_primary_key AS
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PRESCRIPTION_DETAIL ADD CONSTRAINT pk_pharmacy PRIMARY KEY (PRESCRIPTION_ID)';
END add_primary_key;
/

BEGIN
  add_primary_key;
END;
/
